//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceManager.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContoCorrente
    {
        public int ContoId { get; set; }
        public int UserId { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public bool IsCanceled { get; set; }
        public Nullable<System.DateTime> WhenCreated { get; set; }
        public string NameContoCorrente { get; set; }
    }
}
