//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceManager.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimenti
    {
        public int UsciteId { get; set; }
        public int UserId { get; set; }
        public int ContoId { get; set; }
        public int CategoryId { get; set; }
        public decimal TotalAmount { get; set; }
        public bool IsCanceled { get; set; }
        public System.DateTime WhenCreated { get; set; }
        public string Note { get; set; }
        public string Type { get; set; }
    }
}
